enum ActionKind
{
    MoveRight,
    MoveLeft,
    Idle,
    Walking,
    Jumping
}

let jk: jk_ch = null
let rowa: main_ch = null
let mainIdle = null
let mainRunLeft = null
let mainRunRight = null
let level = 0
let enemy_num = 0

// animation rowa
mainRunRight = animation.createAnimation(ActionKind.MoveRight, 200)
mainRunLeft = animation.createAnimation(ActionKind.MoveLeft, 200)
mainIdle = animation.createAnimation(ActionKind.Idle, 200)

class character
{
    entity: Sprite = null
    GRAVITY: number = 294
    VELOCITY: number = 80
    constructor(entity: Sprite)
    {
        this.entity = entity
        this.entity.ay = this.GRAVITY
    }

    set_VELOCITY(VELOCITY: number)
    {
        controller.moveSprite(this.entity,VELOCITY,0)
    }
    
    jump(jump_val: number)
    {
        function func()
        {
            // if character is stand on the platform or ground can jump
            if (this.entity.vy == 0) 
            {
                this.entity.vy = jump_val
            }
        }
        return func
    }

    walk_right(main:any ,frame_1 : any, frame_2: any)
    {
        function func()
        {
            animation.attachAnimation(this.entity, main)
            frame_1
            frame_2
        }
        console.log("I am walking to right")
        return func
    }

    walk_left(main:any ,frame_1 : any, frame_2: any)
    {
        function func()
        {
            //mainRunLeft = animation.createAnimation(ActionKind.MoveLeft, 100)
            animation.attachAnimation(this.entity, main)
            frame_1
            frame_2
        }
        console.log("I am walking to left")
        return func
    }

    idle(main:any, frame_1 : any)
    {
        function func()
        {
            //mainIdle = animation.createAnimation(ActionKind.Idle, 100)
            animation.attachAnimation(this.entity, main)
            frame_1
        }
        console.log("I stay idle")
        return func
    }
}

class main_ch extends character
{
    JUMP: number = -150
    constructor(entity: Sprite)
    {
        super(entity)
        controller.moveSprite(this.entity,this.VELOCITY,0)
        controller.A.onEvent(ControllerButtonEvent.Pressed,this.jump(this.JUMP))
    }

    set_JUMP(JUMP: number)
    {
        controller.A.onEvent(ControllerButtonEvent.Pressed,this.jump(JUMP))
    }

    next()
    {
        function func()
        {
            level += 1
            next_level()
            for (let value of sprites.allOfKind(SpriteKind.Enemy))
            {
                value.destroy()
            }

        }
        return func
    }

    win()
    {
        function func()
        {
            game.over(true, effects.confetti)
        }
        return func
    }

    lose()
    {
        function func()
        {
            game.over(false, effects.melt)
        }
        return func
    }
}

class jk_ch extends character
{ 

    constructor(entity: Sprite)
    {
        super(entity)
        entity.ay = 0
    }

}

function create_rowa ()
{
    rowa = new main_ch(sprites.create(img`
        ................................
        ...........ffffffff.............
        .........ffffffffffff...........
        ........ffffffffffffff..........
        ........ffffff44444ffff.........
        ........ffff44444444fff.........
        .......ffff4444444444ff.........
        .......fff44fff44fff44f.........
        .......fff444ff444ff44f.........
        .......fff444444444444f.........
        .......fff444444444444f.........
        .......ffff4444444444ff.........
        .......fffff444fff44ff..........
        .......ffffff444444ff...........
        ........ffffff4444ff............
        .........fff.ffffff.............
        .........fff..f44f..............
        .........fffffffffff............
        ..........fffeeffeefff..........
        ..........feeeeeeeeeef..........
        ..........feefe88efeef..........
        ..........feefee8efeef..........
        ..........feefeeeefeef..........
        ..........f44feeeef44f..........
        ..........f44fff5ff44f..........
        ...........f4fbbbbf4f...........
        ............ffbbbbff............
        .............fbbbbf.............
        .............fbbfbf.............
        .............fbbfbf.............
        .............fffffff............
        .............feeefeef...........
    `, SpriteKind.Player))
}

/*function enemy_location(input_array: tiles.Location[])
{
    let temp = []
    for(let jk_arr of input_array)
    {
        temp.push([jk_arr.x, jk_arr.y])
    }

    return temp
}*/

function create_enemy()
{
    let tiles_location = tiles.getTilesByType(myTiles.tile8)
    if(level%10 >= 6)
    {
        while(enemy_num < 5)
        {
            jk = new jk_ch(sprites.create(img`
                ................................
                ................................
                ....................ff..........
                ................fffff...........
                ..............fff77f............
                ..............f7fff.............
                ............fff77ff.............
                ...........ff77ff7fff...........
                ....ffffffff77ff77f7ff..........
                ...ff777777777ff77fffff.........
                ...f77777777777777ff............
                ....ffffffffff7777ff............
                .............f7777ffff..........
                ............fff777f77fff........
                ....f......ff5f777ff7fff........
                ....ffffffff555f777fff..........
                ....ffbbbbbf555f777ff...........
                ....ffffffff555f777ffff.........
                ...........f555f777f77ff........
                ...........ff5f77fffffff........
                .....ffffffffff7fffff...........
                ....f5aaaaaaafffaaffff..........
                ....f5aaaaaaaaaaaaaaaff.........
                ....ffffaaaaaaaaaaaaaaff........
                ...ff222ffffffffffffffffffff....
                ...ff222ff...........ff999ff....
                ....fffff............fffffff....
                ................................
                ................................
                ................................
                ................................
                ................................
            `, SpriteKind.Enemy))
            tiles.placeOnTile(jk.entity, tiles_location[enemy_num])
            tiles.setTileAt(tiles_location[enemy_num], myTiles.tile9)
            enemy_num += 1
        }
    }

    else
    {
        while(enemy_num < 2*((level)%10))
        {
            jk = new jk_ch(sprites.create(img`
                ................................
                ................................
                ....................ff..........
                ................fffff...........
                ..............fff77f............
                ..............f7fff.............
                ............fff77ff.............
                ...........ff77ff7fff...........
                ....ffffffff77ff77f7ff..........
                ...ff777777777ff77fffff.........
                ...f77777777777777ff............
                ....ffffffffff7777ff............
                .............f7777ffff..........
                ............fff777f77fff........
                ....f......ff5f777ff7fff........
                ....ffffffff555f777fff..........
                ....ffbbbbbf555f777ff...........
                ....ffffffff555f777ffff.........
                ...........f555f777f77ff........
                ...........ff5f77fffffff........
                .....ffffffffff7fffff...........
                ....f5aaaaaaafffaaffff..........
                ....f5aaaaaaaaaaaaaaaff.........
                ....ffffaaaaaaaaaaaaaaff........
                ...ff222ffffffffffffffffffff....
                ...ff222ff...........ff999ff....
                ....fffff............fffffff....
                ................................
                ................................
                ................................
                ................................
                ................................
            `, SpriteKind.Enemy))
            tiles.placeOnTile(jk.entity, tiles_location[enemy_num])
            tiles.setTileAt(tiles_location[enemy_num], myTiles.tile9)
            enemy_num += 1
        }
    }
}

function rowa_move(mainRunRight:any, mainRunLeft:any, mainIdle:any)
{
    //controll
    controller.right.onEvent(ControllerButtonEvent.Pressed,
    rowa.walk_right(mainRunRight,
                    mainRunRight.addAnimationFrame(img`
                        ................................
                        ...........ffffffff.............
                        .........ffffffffffff...........
                        ........ffffffffffffff..........
                        ........ffffffffffffff..........
                        ........ffffffff4444ff..........
                        .......ffffffff444444ff.........
                        .......fffffff444fff44f.........
                        .......fffffff4444ff44f.........
                        .......fffffff44444444f.........
                        .......fffffff44444444f.........
                        .......fffffff44444444f.........
                        .......fffffff444fff4f..........
                        .......fffffff4444444f..........
                        ........ffffff444444f...........
                        .........fffffffffff............
                        .........ffff.f44f..............
                        .........ffffffeeff.............
                        ..........ff.feeeef.............
                        ...........f.feee8f.............
                        .............feeeef.............
                        .............fe4eef.............
                        .............fe44ef.............
                        .............fe44ef.............
                        .............fffff5.............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............ffffff............
                        ..............feeeef............
                    `),
                    mainRunRight.addAnimationFrame(img`
                        .......ffffffff.......
                        .....ffffffffffff.....
                        ....ffffffffffffff....
                        ....ffffffffffffff....
                        ....ffffffff4444ff....
                        ...ffffffff444444ff...
                        ...fffffff444fff44f...
                        ...fffffff4444ff44f...
                        ...fffffff44444444f...
                        ...fffffff44444444f...
                        ...fffffff44444444f...
                        ...fffffff444fff4f....
                        ...fffffff4444444f....
                        ....ffffff444444f.....
                        .....fffffffffff......
                        .....ffff.f44f........
                        .....ffffffeeff.......
                        ......ff.feeeef.......
                        .......f.feee8f.......
                        .........feeeef.......
                        .........fe4eef.......
                        .........fe44ef.......
                        .........fe44ef.......
                        .........fffff5.......
                        .........fbbbff.......
                        ........ffbbfbf.......
                        ........fbbbfbbf......
                        ........fbbf.fbf......
                        ........fbbf.fbbf.....
                        ........ffffffffff....
                        ........feeeffeeef....
                    `)))
    controller.left.onEvent(ControllerButtonEvent.Pressed,
    rowa.walk_left( mainRunLeft,
                    mainRunLeft.addAnimationFrame(img`
                        ................................
                        .............ffffffff...........
                        ...........ffffffffffff.........
                        ..........ffffffffffffff........
                        ..........ffffffffffffff........
                        ..........ff4444ffffffff........
                        .........ff444444ffffffff.......
                        .........f44fff444fffffff.......
                        .........f44ff4444fffffff.......
                        .........f44444444fffffff.......
                        .........f44444444fffffff.......
                        .........f44444444fffffff.......
                        ..........f4fff444fffffff.......
                        ..........f4444444fffffff.......
                        ...........f444444ffffff........
                        ............fffffffffff.........
                        ..............f44f.ffff.........
                        .............ffeeffffff.........
                        .............feeeef.ff..........
                        .............f8eeef.f...........
                        .............feeeef.............
                        .............fee4ef.............
                        .............fe44ef.............
                        .............fe44ef.............
                        .............5fffff.............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ............ffffff..............
                        ............feeeef..............
                    `),
                    mainRunLeft.addAnimationFrame(img`
                        .......ffffffff.......
                        .....ffffffffffff.....
                        ....ffffffffffffff....
                        ....ffffffffffffff....
                        ....ff4444ffffffff....
                        ...ff444444ffffffff...
                        ...f44fff444fffffff...
                        ...f44ff4444fffffff...
                        ...f44444444fffffff...
                        ...f44444444fffffff...
                        ...f44444444fffffff...
                        ....f4fff444fffffff...
                        ....f4444444fffffff...
                        .....f444444ffffff....
                        ......fffffffffff.....
                        ........f44f.ffff.....
                        .......ffeeffffff.....
                        .......feeeef.ff......
                        .......f8eeef.f.......
                        .......feeeef.........
                        .......fee4ef.........
                        .......fe44ef.........
                        .......fe44ef.........
                        .......5fffff.........
                        .......ffbbbf.........
                        .......fbfbbff........
                        ......fbbfbbbf........
                        ......fbf.fbbf........
                        .....fbbf.fbbf........
                        ....ffffffffff........
                        ....feeeffeeef........
                    `)))

    controller.right.onEvent(ControllerButtonEvent.Released,
    rowa.idle(      mainIdle,
                    mainIdle.addAnimationFrame(img`
                        ................................
                        ...........ffffffff.............
                        .........ffffffffffff...........
                        ........ffffffffffffff..........
                        ........ffffff44444ffff.........
                        ........ffff44444444fff.........
                        .......ffff4444444444ff.........
                        .......fff44fff44fff44f.........
                        .......fff444ff444ff44f.........
                        .......fff444444444444f.........
                        .......fff444444444444f.........
                        .......ffff4444444444ff.........
                        .......fffff444fff44ff..........
                        .......ffffff444444ff...........
                        ........ffffff4444ff............
                        .........fff.ffffff.............
                        .........fff..f44f..............
                        .........fffffffffff............
                        ..........fffeeffeefff..........
                        ..........feeeeeeeeeef..........
                        ..........feefe88efeef..........
                        ..........feefee8efeef..........
                        ..........feefeeeefeef..........
                        ..........f44feeeef44f..........
                        ..........f44fff5ff44f..........
                        ...........f4fbbbbf4f...........
                        ............ffbbbbff............
                        .............fbbbbf.............
                        .............fbbfbf.............
                        .............fbbfbf.............
                        .............fffffff............
                        .............feeefeef...........
                    `)))
    controller.left.onEvent(ControllerButtonEvent.Released,
    rowa.idle(      mainIdle,
                    mainIdle.addAnimationFrame(img`
                        ................................
                        ...........ffffffff.............
                        .........ffffffffffff...........
                        ........ffffffffffffff..........
                        ........ffffff44444ffff.........
                        ........ffff44444444fff.........
                        .......ffff4444444444ff.........
                        .......fff44fff44fff44f.........
                        .......fff444ff444ff44f.........
                        .......fff444444444444f.........
                        .......fff444444444444f.........
                        .......ffff4444444444ff.........
                        .......fffff444fff44ff..........
                        .......ffffff444444ff...........
                        ........ffffff4444ff............
                        .........fff.ffffff.............
                        .........fff..f44f..............
                        .........fffffffffff............
                        ..........fffeeffeefff..........
                        ..........feeeeeeeeeef..........
                        ..........feefe88efeef..........
                        ..........feefee8efeef..........
                        ..........feefeeeefeef..........
                        ..........f44feeeef44f..........
                        ..........f44fff5ff44f..........
                        ...........f4fbbbbf4f...........
                        ............ffbbbbff............
                        .............fbbbbf.............
                        .............fbbfbf.............
                        .............fbbfbf.............
                        .............fffffff............
                        .............feeefeef...........
                    `)))
}

function jk_move()
{   
    let jk_array = sprites.allOfKind(SpriteKind.Enemy) // คือ array ของ jk ที่อยู่ในฉาก
    for(let enemy of jk_array)
    {
        if(level%10 <= 5)
        {
            if (Math.abs(enemy.x - rowa.entity.x) < 70)
            {
                if (enemy.x - rowa.entity.x < -5)
                {
                    enemy.vx = 10
                }
                else if (enemy.x - rowa.entity.x > 5)
                {
                    enemy.vx = -10
                }
                if (enemy.y - rowa.entity.y < -5)
                {
                    enemy.vy = 10
                }
                else if (enemy.y - rowa.entity.y > 5)
                {
                    enemy.vy = -10
                }
            }
            else
            {
                enemy.vx = 0
                enemy.vy = 0
            }
        }
        else
        {
            if (Math.abs(enemy.x - rowa.entity.x) < 70)
            {
                if (enemy.x - rowa.entity.x < -5)
                {
                    enemy.vx = 10*5
                }
                else if (enemy.x - rowa.entity.x > 5)
                {
                    enemy.vx = -10*5
                }
                if (enemy.y - rowa.entity.y < -5)
                {
                    enemy.vy = 10*5
                }
                else if (enemy.y - rowa.entity.y > 5)
                {
                    enemy.vy = -10*5
                }
            }
            else
            {
                enemy.vx = 0
                enemy.vy = 0
            }
        }
    }
}

// start game
create_rowa() // สร้าง rowa
rowa_move(mainRunRight, mainRunLeft, mainIdle) // จัดการเกี่ยวกับการเคลื่อนไหวของ rowa
next_level() // จัดการเกี่ยวกับฉาก
//create_enemy() // สร้างศัตรู
scene.onOverlapTile(SpriteKind.Player, myTiles.tile11, rowa.lose()) // ตกหลุมตาย
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, rowa.lose()) // โดน jk ตาย
scene.onOverlapTile(SpriteKind.Player, myTiles.tile4, rowa.next()) // เข้าเส้นชัยชนะ

// updating game
game.onUpdate(
function ()
{
    create_enemy()
    jk_move()
    scene.centerCameraAt(rowa.entity.x, 0)
    if (rowa.entity.vx > 0 && rowa.entity.vy == 0)
    {
        animation.setAction(rowa.entity, ActionKind.MoveRight)
    }
    else if (rowa.entity.vx < 0 && rowa.entity.vy == 0)
    {
        animation.setAction(rowa.entity, ActionKind.MoveLeft)
    }
    else
    {
        animation.setAction(rowa.entity, ActionKind.Idle)
    }

    if(level%10 >= 6)
    {
        rowa.set_VELOCITY(160)
        rowa.set_JUMP(-200)
    }
    else
    {
        rowa.set_VELOCITY(rowa.VELOCITY)
        rowa.set_JUMP(rowa.JUMP)
    }
})
