// *******************moving character*******************
function rowa_move(mainRunRight:any, mainRunLeft:any, mainIdle:any)
{
    //controll
    controller.right.onEvent(ControllerButtonEvent.Pressed,
    rowa.walk_right(mainRunRight,
                    mainRunRight.addAnimationFrame(img`
                        ................................
                        ...........ffffffff.............
                        .........ffffffffffff...........
                        ........ffffffffffffff..........
                        ........ffffffffffffff..........
                        ........ffffffff4444ff..........
                        .......ffffffff444444ff.........
                        .......fffffff444fff44f.........
                        .......fffffff4444ff44f.........
                        .......fffffff44444444f.........
                        .......fffffff44444444f.........
                        .......fffffff44444444f.........
                        .......fffffff444fff4f..........
                        .......fffffff4444444f..........
                        ........ffffff444444f...........
                        .........fffffffffff............
                        .........ffff.f44f..............
                        .........ffffffeeff.............
                        ..........ff.feeeef.............
                        ...........f.feee8f.............
                        .............feeeef.............
                        .............fe4eef.............
                        .............fe44ef.............
                        .............fe44ef.............
                        .............fffff5.............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............ffffff............
                        ..............feeeef............
                    `),
                    mainRunRight.addAnimationFrame(img`
                        .......ffffffff.......
                        .....ffffffffffff.....
                        ....ffffffffffffff....
                        ....ffffffffffffff....
                        ....ffffffff4444ff....
                        ...ffffffff444444ff...
                        ...fffffff444fff44f...
                        ...fffffff4444ff44f...
                        ...fffffff44444444f...
                        ...fffffff44444444f...
                        ...fffffff44444444f...
                        ...fffffff444fff4f....
                        ...fffffff4444444f....
                        ....ffffff444444f.....
                        .....fffffffffff......
                        .....ffff.f44f........
                        .....ffffffeeff.......
                        ......ff.feeeef.......
                        .......f.feee8f.......
                        .........feeeef.......
                        .........fe4eef.......
                        .........fe44ef.......
                        .........fe44ef.......
                        .........fffff5.......
                        .........fbbbff.......
                        ........ffbbfbf.......
                        ........fbbbfbbf......
                        ........fbbf.fbf......
                        ........fbbf.fbbf.....
                        ........ffffffffff....
                        ........feeeffeeef....
                    `)))
    controller.left.onEvent(ControllerButtonEvent.Pressed,
    rowa.walk_left( mainRunLeft,
                    mainRunLeft.addAnimationFrame(img`
                        ................................
                        .............ffffffff...........
                        ...........ffffffffffff.........
                        ..........ffffffffffffff........
                        ..........ffffffffffffff........
                        ..........ff4444ffffffff........
                        .........ff444444ffffffff.......
                        .........f44fff444fffffff.......
                        .........f44ff4444fffffff.......
                        .........f44444444fffffff.......
                        .........f44444444fffffff.......
                        .........f44444444fffffff.......
                        ..........f4fff444fffffff.......
                        ..........f4444444fffffff.......
                        ...........f444444ffffff........
                        ............fffffffffff.........
                        ..............f44f.ffff.........
                        .............ffeeffffff.........
                        .............feeeef.ff..........
                        .............f8eeef.f...........
                        .............feeeef.............
                        .............fee4ef.............
                        .............fe44ef.............
                        .............fe44ef.............
                        .............5fffff.............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ..............fbbf..............
                        ............ffffff..............
                        ............feeeef..............
                    `),
                    mainRunLeft.addAnimationFrame(img`
                        .......ffffffff.......
                        .....ffffffffffff.....
                        ....ffffffffffffff....
                        ....ffffffffffffff....
                        ....ff4444ffffffff....
                        ...ff444444ffffffff...
                        ...f44fff444fffffff...
                        ...f44ff4444fffffff...
                        ...f44444444fffffff...
                        ...f44444444fffffff...
                        ...f44444444fffffff...
                        ....f4fff444fffffff...
                        ....f4444444fffffff...
                        .....f444444ffffff....
                        ......fffffffffff.....
                        ........f44f.ffff.....
                        .......ffeeffffff.....
                        .......feeeef.ff......
                        .......f8eeef.f.......
                        .......feeeef.........
                        .......fee4ef.........
                        .......fe44ef.........
                        .......fe44ef.........
                        .......5fffff.........
                        .......ffbbbf.........
                        .......fbfbbff........
                        ......fbbfbbbf........
                        ......fbf.fbbf........
                        .....fbbf.fbbf........
                        ....ffffffffff........
                        ....feeeffeeef........
                    `)))

    controller.right.onEvent(ControllerButtonEvent.Released,
    rowa.idle(      mainIdle,
                    mainIdle.addAnimationFrame(img`
                        ................................
                        ...........ffffffff.............
                        .........ffffffffffff...........
                        ........ffffffffffffff..........
                        ........ffffff44444ffff.........
                        ........ffff44444444fff.........
                        .......ffff4444444444ff.........
                        .......fff44fff44fff44f.........
                        .......fff444ff444ff44f.........
                        .......fff444444444444f.........
                        .......fff444444444444f.........
                        .......ffff4444444444ff.........
                        .......fffff444fff44ff..........
                        .......ffffff444444ff...........
                        ........ffffff4444ff............
                        .........fff.ffffff.............
                        .........fff..f44f..............
                        .........fffffffffff............
                        ..........fffeeffeefff..........
                        ..........feeeeeeeeeef..........
                        ..........feefe88efeef..........
                        ..........feefee8efeef..........
                        ..........feefeeeefeef..........
                        ..........f44feeeef44f..........
                        ..........f44fff5ff44f..........
                        ...........f4fbbbbf4f...........
                        ............ffbbbbff............
                        .............fbbbbf.............
                        .............fbbfbf.............
                        .............fbbfbf.............
                        .............fffffff............
                        .............feeefeef...........
                    `)))
    controller.left.onEvent(ControllerButtonEvent.Released,
    rowa.idle(      mainIdle,
                    mainIdle.addAnimationFrame(img`
                        ................................
                        ...........ffffffff.............
                        .........ffffffffffff...........
                        ........ffffffffffffff..........
                        ........ffffff44444ffff.........
                        ........ffff44444444fff.........
                        .......ffff4444444444ff.........
                        .......fff44fff44fff44f.........
                        .......fff444ff444ff44f.........
                        .......fff444444444444f.........
                        .......fff444444444444f.........
                        .......ffff4444444444ff.........
                        .......fffff444fff44ff..........
                        .......ffffff444444ff...........
                        ........ffffff4444ff............
                        .........fff.ffffff.............
                        .........fff..f44f..............
                        .........fffffffffff............
                        ..........fffeeffeefff..........
                        ..........feeeeeeeeeef..........
                        ..........feefe88efeef..........
                        ..........feefee8efeef..........
                        ..........feefeeeefeef..........
                        ..........f44feeeef44f..........
                        ..........f44fff5ff44f..........
                        ...........f4fbbbbf4f...........
                        ............ffbbbbff............
                        .............fbbbbf.............
                        .............fbbfbf.............
                        .............fbbfbf.............
                        .............fffffff............
                        .............feeefeef...........
                    `)))
}

function jk_move()
{   
    let jk_array = sprites.allOfKind(EnemyKind.JK) // คือ array ของ jk ที่อยู่ในฉาก
    let play = null
    
    jkRunRight = animation.createAnimation(ActionKind_jk.MoveRight, 200)
    jkRunLeft = animation.createAnimation(ActionKind_jk.MoveLeft, 200)
    jkIdle = animation.createAnimation(ActionKind_jk.Idle, 200)

    for(let enemy of jk_array_)
    {
        //set_Action(enemy, ActionKind_jk.moveRight, ActionKind_jk.moveLeft, ActionKind_jk.idle)
        // animation jk

        if(level%10 <= 5)
        {
            if (Math.abs(enemy.entity.x - rowa.entity.x) < 70)
            {
                if (enemy.entity.x - rowa.entity.x < -5)
                {
                    state[0] = state[1]
                    state[1] = true
                    enemy.entity.vx = 10
                }
                else if (enemy.entity.x - rowa.entity.x > 5)
                {
                    state[0] = state[1]
                    state[1] = false
                    enemy.entity.vx = -10
                }
                if (enemy.entity.y - rowa.entity.y < -5)
                {
                    enemy.entity.vy = 10
                }
                else if (enemy.entity.y - rowa.entity.y > 5)
                {
                    
                    enemy.entity.vy = -10
                }
            }
            else
            {
                enemy.entity.vx = 0
                enemy.entity.vy = 0
            }
        }
        else
        {
            if (Math.abs(enemy.entity.x - rowa.entity.x) < 70)
            {
                if (enemy.entity.x - rowa.entity.x < -5)
                {
                    enemy.entity.vx = 10*5
                }
                else if (enemy.entity.x - rowa.entity.x > 5)
                {
                    enemy.entity.vx = -10*5
                }
                if (enemy.entity.y - rowa.entity.y < -5)
                {
                    enemy.entity.vy = 10*5
                }
                else if (enemy.entity.y - rowa.entity.y > 5)
                {
                    enemy.entity.vy = -10*5
                }
            }
            else
            {
                enemy.entity.vx = 0
                enemy.entity.vy = 0
            }
        }
        
        play = state[0]&&!state[1] || !state[0]&&state[1]
        if(play)
        {
                animation.runImageAnimation(
                enemy.entity,
                [img`
                    ................................
                    ................................
                    ....................ff..........
                    ................fffff...........
                    ..............fff77f............
                    ..............f7fff.............
                    ............fff77ff.............
                    ...........ff77ff7fff...........
                    ....ffffffff77ff77f7ff..........
                    ...ff777777777ff77fffff.........
                    ...f77777777777777ff............
                    ....ffffffffff7777ff............
                    .............f7777ffff..........
                    ............fff777f77fff........
                    ....f......ff5f777ff7fff........
                    ....ffffffff555f777fff..........
                    ....ffbbbbbf555f777ff...........
                    ....ffffffff555f777ffff.........
                    ...........f555f777f77ff........
                    ...........ff5f77fffffff........
                    .....ffffffffff7fffff...........
                    ....f5aaaaaaafffaaffff..........
                    ....f5aaaaaaaaaaaaaaaff.........
                    ....ffffaaaaaaaaaaaaaaff........
                    ...ff222ffffffffffffffffffff.dd.
                    ...ff222ff...........ff999ff.dd.
                    ....fffff............fffffff.dd.
                    ................................
                    ................................
                    ................................
                    ................................
                    ................................
                `, img`
                    ................................
                    ................................
                    ....................ff..........
                    ................fffff...........
                    ..............fff77f............
                    ..............f7fff.............
                    ............fff77ff.............
                    ...........ff77ff7fff...........
                    ....ffffffff77ff77f7ff..........
                    ...ff777777777ff77fffff.........
                    ...f77777777777777ff............
                    ....ffffffffff7777ff............
                    .............f7777ffff..........
                    ............fff777f77fff........
                    ....f......ff5f777ff7fff........
                    ....ffffffff555f777fff..........
                    ....ffbbbbbf555f777ff...........
                    ....ffffffff555f777ffff.........
                    ...........f555f777f77ff........
                    ...........ff5f77fffffff........
                    .....ffffffffff7fffff...........
                    ....f5aaaaaaafffaaffff..........
                    ....f5aaaaaaaaaaaaaaaff......ddd
                    ....ffffaaaaaaaaaaaaaaff.....d.d
                    ...ff222ffffffffffffffffffff.d.d
                    ...ff222ff...........ff999ffdd.d
                    ....fffff............fffffffdd.d
                    ..............................dd
                    ................................
                    ................................
                    ................................
                    ................................
                `, img`
                    ................................
                    ................................
                    ....................ff..........
                    ................fffff...........
                    ..............fff77f............
                    ..............f7fff.............
                    ............fff77ff.............
                    ...........ff77ff7fff...........
                    ....ffffffff77ff77f7ff..........
                    ...ff777777777ff77fffff.........
                    ...f77777777777777ff............
                    ....ffffffffff7777ff............
                    .............f7777ffff..........
                    ............fff777f77fff........
                    ....f......ff5f777ff7fff........
                    ....ffffffff555f777fff..........
                    ....ffbbbbbf555f777ff...........
                    ....ffffffff555f777ffff.........
                    ...........f555f777f77ff........
                    ...........ff5f77fffffff........
                    .....ffffffffff7fffff...........
                    ....f5aaaaaaafffaaffff........dd
                    ....f5aaaaaaaaaaaaaaaff......ddd
                    ....ffffaaaaaaaaaaaaaaff.....d.d
                    ...ff222ffffffffffffffffffff.d.d
                    ...ff222ff...........ff999ffd..d
                    ....fffff............fffffffd..d
                    ............................d..d
                    ............................dddd
                    ................................
                    ................................
                    ................................
                `],
                500,
                !state[1]
                )
                
                if(state[1])
                {
                    animation.runImageAnimation(
                    enemy.entity,
                    [img`
                        ................................
                        ................................
                        ..........ff....................
                        ...........ffffff...............
                        ............f77ffff.............
                        .............ffffff.............
                        .............ff77ffff...........
                        ...........fff7ff777ff..........
                        ..........ff7f777ff77ffffffff...
                        .........fffff777ff777777777ff..
                        ............ff777777777777777f..
                        ............ff77777ffffffffff...
                        ..........ffff77777f............
                        ........fff77f777ffff...........
                        ........fff7ff777ff5ff......f...
                        ..........fff77775555ffffffff...
                        ...........ff77775555fbbbbbff...
                        .........ffff77775555ffffffff...
                        ........ff77f77775555f..........
                        ........fffffff77ff5ff..........
                        ...........fffffffffffffffff....
                        ..........ffffaaafffaaaaaaa5f...
                        .........ffaaaaaaaaaaaaaaaa5f...
                        ........ffaaaaaaaaaaaaaaaffff...
                        .dd.fffffffffffffffffffff222ff..
                        .dd.ff999ff............ff222ff..
                        .dd.fffffff.............fffff...
                        ................................
                        ................................
                        ................................
                        ................................
                        ................................
                    `,img`
                        ................................
                        ................................
                        ..........ff....................
                        ...........fffff................
                        ............f77fff..............
                        .............fff7f..............
                        .............ff77fff............
                        ...........fff7ff77ff...........
                        ..........ff7f77ff77ffffffff....
                        .........fffff77ff777777777ff...
                        ............ff77777777777777f...
                        ............ff7777ffffffffff....
                        ..........ffff7777f.............
                        ........fff77f777fff............
                        ........fff7ff777f5ff......f....
                        ..........fff777f555ffffffff....
                        .........ffff777f555ffffffff....
                        ........ff77f777f555f...........
                        ........fffffff77f5ff...........
                        ...........fffff7ffffffffff.....
                        ..........ffffaafffaaaaaaa5f....
                        ddd......ffaaaaaaaaaaaaaaa5f....
                        d.d.....ffaaaaaaaaaaaaaaffff....
                        d.d.ffffffffffffffffffff222ff...
                        d.ddff999ff...........ff222ff...
                        d.ddfffffff............fffff....
                        dd..............................
                        ................................
                        ................................
                        ................................
                        ................................
                        ................................
                    `,img`
    ................................
    ................................
    ..........ff....................
    ...........fffff................
    ............f77fff..............
    .............fff7f..............
    .............ff77fff............
    ...........fff7ff77ff...........
    ..........ff7f77ff77ffffffff....
    .........fffff77ff777777777ff...
    ............ff77777777777777f...
    ............ff7777ffffffffff....
    ..........ffff7777f.............
    ........fff77f777fff............
    ........fff7ff777f5ff......f....
    ..........fff777f555ffffffff....
    ...........ff777f555fbbbbbff....
    .........ffff777f555ffffffff....
    ........ff77f777f555f...........
    ........fffffff77f5ff...........
    ...........fffff7ffffffffff.....
    dd........ffffaafffaaaaaaa5f....
    ddd......ffaaaaaaaaaaaaaaa5f....
    d.d.....ffaaaaaaaaaaaaaaffff....
    d.d.ffffffffffffffffffff222ff...
    d..dff999ff...........ff222ff...
    d..dfffffff............fffff....
    d..d............................
    dddd............................
    ................................
    ................................
    ................................
                    `],
                    500,
                    state[1]
                    )
                }
        }
        //console.log(state)
        //console.log(play)
    }


}
// **************************************

function dango_move()
{
    if (Math.abs(dango.entity.x - rowa.entity.x) < 100)
    {
        if (dango.entity.x - rowa.entity.x < -5)
        {
            dango.entity.vx = 10*8
        }
        else if (dango.entity.x - rowa.entity.x > 5)
        {
            dango.entity.vx = -10*8
        }
        if (dango.entity.y - rowa.entity.y < -5)
        {
            dango.entity.vy = 10*8
        }
        else if (dango.entity.y - rowa.entity.y > 5)
        {
                    
            dango.entity.vy = -10*8
        }
    }
}